import os
from os.path import join, isdir
import shutil
from tkinter import filedialog as fd
from rich.progress import track
from rich import print as rprint

# This script remove all non-tiff files generated by the ONI microscope

# To install rich for the progress bar, run the following in command line:
# python -m pip install rich

rprint("[red]Choose an experiment folder[red]")
folderpath = fd.askdirectory(
    initialdir="/Volumes/lsa-nwalter/Guoming_Gao_turbo/Walterlab_server/RAW_DATA/DEFAULT_USER"
)

print("Now organizing:\n", folderpath)

for subfolder in track(os.listdir(folderpath)):
    if isdir(join(folderpath, subfolder)):
        target_folder = join(
            folderpath,
            subfolder,
            "pos_0",
        )
        target_tif_fname = [f for f in os.listdir(target_folder) if f.endswith(".tif")][
            0
        ]
        shutil.copy(
            join(target_folder, target_tif_fname),
            join(folderpath, subfolder + ".tif"),
        )
